In [20]:
#1 
import numpy as np
from colorama import Fore, Back, Style
a=int(input("donnez le nombre de lignes:"))
b=int(input("donnez le nombre des colomne:"))
c=int(input("Donnez la longeur de votre liste:"))
k=np.arange(c).reshape(a,b)
l=k.tolist()
print(Fore.RED+"your array: ",k)
print(Fore.GREEN+"your list: ",l)

donnez le nombre de lignes:3
donnez le nombre des colomne:5
Donnez la longeur de votre liste:15
your array:  [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
your list:  [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]


In [4]:
#2
import numpy as np
from colorama import Fore, Back, Style
array=np.random.uniform(2, 10, size=(3,3))
trace = np.diagonal(array)
print("your array:",array)
print(Fore.RED+"Diagonal elements are:",trace)
print(Fore.GREEN+"Sum of Diagonal elements is:",sum(trace))

your array: [[6.24635858 5.62171228 7.46693103]
 [9.9948954  7.742704   6.42659931]
 [7.08793301 2.60706468 8.06793924]]
Diagonal elements are: [6.24635858 7.742704   8.06793924]
Sum of Diagonal elements is: 22.057001818348695


In [20]:
#3
import numpy as np
from colorama import Fore, Back, Style
a = np.array([[1,25,3],[11,5,22]])
x=3
print("your array: ",a)
print(Fore.GREEN+"values bigger than:",a[a>x])

your array:  [[ 1 25  3]
 [11  5 22]]
values bigger than: [25 11  5 22]


In [25]:
#4
import numpy as np
from colorama import Fore, Back, Style
A=np.array([1,2,3,55])
b=np.array([4,5,6,-1])

for i in range(len(A)):
    for j in range(len(b)):
        c=np.array(A+b)
        
print("Array A:",A)
print("Array B:",b)
print(Fore.GREEN+"Array C: ",c)

Array A: [ 1  2  3 55]
Array B: [ 4  5  6 -1]
Array C:  [ 5  7  9 54]


In [8]:
#5
import numpy as np
from colorama import Fore, Back, Style
x = np.array([[10, 30], [20, 60]])
print("Original array:")
print(x)
print(Fore.GREEN+"Mean of each column:")
print(x.mean(axis=0))
print(Fore.BLUE+"Mean of each row:")
print(x.mean(axis=1))

Original array:
[[10 30]
 [20 60]]
Mean of each column:
[15. 45.]
Mean of each row:
[20. 40.]
